### ISSUE TITLE
[suggestion] Inheritance icons & default icon for file

### ISSUE THREAD

**Issue by Mara-Li** [FlorianWoelki/obsidian-icon-folder#12]
It will be good to have an option to inherit icons in file and folder.

Also, to add a default icon for file, icons will be removed when changed.

Image example :

![image](https://user-images.githubusercontent.com/30244939/140603460-af3e71a6-b2c9-4327-abee-72eacd78b229.png)
Note : By default, my note have a default icons (added with css for the moment), but I add a specific icon for "Relation notes"

For the moment, I do this : 
```css
.nav-file-title:not(.nav-file-title.is-unsupported) .nav-file-title-content:before {
    content: "\ea37";
    font-family: boxicons;
    font-size: calc(var(--size) + 3%);
    margin-right: 5px;
    margin-left: 0px;
    vertical-align: -2px;
}

.nav-file-title-content[data-link-data-href="file_name"]::before {
    content: '' !important;
    margin-right: 0 !important;
}
```
I think, for theme compatibility, add a class/id in folder-file modified by the plugin, so you can work with this class to remove the content.
