### ISSUE TITLE
New Modal Design

### ISSUE THREAD

**Issue by ShahriarKh** [FlorianWoelki/obsidian-icon-folder#19]
![image](https://user-images.githubusercontent.com/31452340/147343069-a88a24cf-aba5-47ce-ba83-258a933de4fa.png)

```css
.prompt-results {
    /* list-style: none; */
    margin: 0;
    overflow-y: auto;
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(120px, 1fr));
    grid-auto-rows: 90px;
}

.suggestion-item {
   /*  position: relative; */
    cursor: pointer;
    white-space: pre-wrap;
    display: flex;
    justify-content: flex-end;
    align-items: center;
    flex-direction: column-reverse;
    text-align: center;
    font-size: 13px;
    color: gray;
    padding: 16px 8px;
    line-break: auto;
    word-break: break-word;
    line-height: 1.3;
}

.obsidian-icon-folder-icon-preview svg {
    width: 24px;
    height: 24px;
    color: white;
    margin-bottom: 4px;
}
```

# Motivation:
More items per line => Shorter scroll
Box view for every icon => Easier on eye
Smaller and duller text => It's easier to look for icons than looking for their name
