### ISSUE TITLE
[BUG] White icon in white theme

### ISSUE THREAD

**Issue by Mara-Li** [FlorianWoelki/obsidian-icon-folder#21]
Hello !
The new modal is pretty cool... But there is a display problem : All icon are white.
So, on white theme, it can be a problem !

![image](https://user-images.githubusercontent.com/30244939/147413410-3be5e282-b43f-4304-a860-f48c0374c617.png)

The best way is to change here : 
```css
.obsidian-icon-folder-icon-preview svg {
 color: white;
}
```
to
```css
.obsidian-icon-folder-icon-preview svg {
 color: currentColor;
}
```

With this I get that : 
(white theme)
![image](https://user-images.githubusercontent.com/30244939/147413450-42b6c322-0b05-425e-a1e6-888f36001532.png)

(black theme)
![image](https://user-images.githubusercontent.com/30244939/147413471-246e1451-9e6c-4ec3-9bc9-0669735ed42a.png)
